"""page text store

Revision ID: f0f4d21dbb53
Revises: e7b4c1a92d58
Create Date: 2026-08-04 13:08:02.279974

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0f4d21dbb53"
down_revision: Union[str, Sequence[str], None] = "e7b4c1a92d58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page_texts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("ocr_engine", sa.String(length=32), nullable=False),
        sa.Column("extract_ok", sa.Boolean(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "page", name="uq_page_texts_document_page"),
    )
    op.create_index(op.f("ix_page_texts_document_id"), "page_texts", ["document_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_page_texts_document_id"), table_name="page_texts")
    op.drop_table("page_texts")
    # ### end Alembic commands ###
