groups = {
    "1": [
        "Medical Progress Reports (PR-2)",
        "Supplemental Report on Pain Management Process",
        "Physical Examination Reevaluation",
        "Supplemental Report",
        "Progress Notes",
        "Physician Notes",
        "Telephone Appointment Visit",
        "Transplant Follow Up",
        "Nephrology Consult Note",
        "Follow up Video Visit",
        "Post Operative Visit",
        "Preoperative Hospital Admission History and Physical",
        "Orthopedic Re-evaluation",
        "Progress Report",
        "Treating Orthopedic Evaluation",
        "Orthopedic Follow Up",
        "Admission History & Physical",
        "Family Medicine Clinic Note",
        "Outpatient Palliative Care Consult",
        "PRIMARY TREATING PHYSICIAN'S PROGRESS REPORT (PR-2)",
        "Encounter - Office Visit",
        "Office Visit",
        "Encounter Office Visit",
        "Telephone Visit",
        "Initial Comprehensive Examination",
    ],
    "2": [
        "Primary Treating Physician’s Permanent and Stationary Report (PR-4)",
        "Primary Treating Physician's Maximum Medical Improvement for Impairment Rating Purposes",
        "Doctor’s First Report of Occupational Injury or Illness",
        "Consultative Rating Determination",
        "Initial Patient Consultation",
        "Specialist Initial Consultation",
        "Initial Orthopedic Consultation",
    ],
    "3": [
        "Diagnostic Study (X-Ray, MRI, CT scan…)",
        "Laboratory Report",
        "Bilateral Mammogram Screening",
        "Diabetic Muscle Infraction",
        "Ed (Emergency Department) Provider Notes",
        "Dexa Bone Density, Hip and Spine",
        "NCS/EMG Report",
        "Unattended Sleep Study",
        "Auto CPAP",
        "Colonoscopy Report",
        "X-Ray Report",
        "X Ray Report",
        "XRay Report",
        "MRI Report",
        "CT Scan",
        "CT Scan Report",
        "XR Wrist Minimum 3 Views",
        "Diagnostic Study",
        "Diagnostic",
        "MRI Lumbar Spine w/o Contrast",
        "MRI Lumbar Spine",
        "MRI Lumbar",
        "MRI Left Shoulder w/o Contrast",
        "MRI Left Shoulder",
        "MRI Shoulder",
        "Electrodiagnostic Study",
        "MRI Right Shoulder w/o Contrast",
        "MRI Right Shoulder",
        "MRI Lumbar Spine Without Contrast",
        "MRI Lumbar Spine",
    ],
    "4": ["GI Outpatient Procedure H&P"],
    "5": [
        "Initial Acupuncture Intake Form",
        "Initial Chiropractic Evaluation",
        "Chiropractic Progress Report",
        "Acupuncture Worksheet Established",
        "Acupuncture Worksheet Final",
        "Chiropractic Evaluation",
        "History of Present Illness",
        "Physical Examination",
        "Diagnosis",
        "Physical Therapy Note",
        "Physical Therapy Daily Note",
        "SOAP Notes",
        "PT initial Report",
        "PT Daily",
        "PT Progress",
        "Chiropractor Notes",
        "Acupuncture Daily",
        "Daily Encounter",
    ],
    "6": [],
    "7": [
        "Worker’s Compensation Claim Form",
        "Application of Adjudication of Claim",
        "Amended Application for Adjudication of Claim",
    ],
    "8": ["Surgical Pathology Report", "Operative Report", "Oversight Physician Report"],
    "9": ["Deposition", "Video Conference Deposition", "Deposition Transcript", "Transcript"],
    "10": ["RFA (Request For Authorization)"],
    "11": ["Comprehensive Interval History Form", "Medical Decision Making"],
    "12": ["QME/AME Supplemental Reports", "Supplemental Reports"],
    "13": [
        "QME/AME reports",
        "QME reports",
        "AME reports",
    ],
    "14": ["Results"],
    "Group 100": ["Everything else", "General Documents"],
}
